\. crear_tablas.sql
\. insertar.sql
\. BorradoAutomaticoPrerreserva.sql
\. FinalizadoAutomatico.sql
\. ProcedureAnularReserva.sql
\. ProcedureConsultarDatos.sql
\. ProcedureConsultarEventosDisponibles.sql
\. ProcedureConsultarEventos.sql
\. ProcedureConsultarGradasDelEvento.sql
\. ProcedureConsultarMisReservasActivas.sql
\. ProcedureConsultarMisReservas.sql
\. ProcedureDesconectarse.sql
\. ProcedureIniciarSesion.sql
\. ProcedureModificarDatos.sql
\. ProcedurePagarReserva.sql
\. ProcedurePrerreservar.sql
\. ProcedureRegistrarse.sql
\! clear
